name: aquarium_control
description: App to control aquarium lights
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.0.3
  permission_handler: ^10.2.0
  bluetooth_enable_fork: ^0.1.6
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true